name: Reusable Deploy
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      port:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install & Build
        run: |
          npm ci
          npm run build --if-present
          npm test --if-present

      - name: Deploy with Docker
        run: |
          echo "Deploying ${{ inputs.app-name }} on port ${{ inputs.port }}"
          docker build -t ${{ inputs.app-name }}:latest.
          docker stop ${{ inputs.app-name }} || true
          docker rm ${{ inputs.app-name }} || true
          docker run -d --restart always --name ${{ inputs.app-name }} -p ${{ inputs.port }}:${{ inputs.port }} ${{ inputs.app-name }}:latest
